### ISSUE TITLE
How to manage images?

### ISSUE THREAD

**Issue by rubyless** [adunkman/connect-assets#300]
HI,
How to manage images?

**Comment by nmalacarne** [comment]
You can add your image path to connect-assets via the path config option, e.g.

```
...

var assets = require('connect-assets');

app.use(assets({
  path: [
    'assets/css',
    'assets/js'
    'assets/img'
  ] 
}));
```

**Comment by fpereira1** [comment]
nice

**Comment by adunkman** [comment]
Thanks @nmalacarne!

**Comment by eruanntion** [comment]
HI,

How to access those image files from within scss (SASS) files? Is there a support for assetPath helper from within sass files? If yes, what is the proper syntax (and additional configuration if needed)?

**Comment by nmalacarne** [comment]
@eruanntion The `asset_path` function was added in #251 and should work for you in SASS.

You will need to add your image path to the connect-assets as stated above. When using `asset_path`, you do not need to pass the entire path, just the image name, e.g. (using stylus):

```
body
  background-image url(asset_path('image-name.png'))
```

**Comment by eruanntion** [comment]
Tried it, but it doesn't work. It doesn't compile at all. Also tried to use camel case `assetPath` instead of `asset_path`, but that doesn't work either. Then I tried to enable macros directly on mincer:

`    Mincer.MacroProcessor.configure(['.js', '.css', 'scss']); ` 

and used this syntax:

`    '$$ expression $$'     `

It works without problem inside .js files, but again, it doesn't work for sass. I'm using connect-assets 5.0.1.

Any ideas? 
Thnx!

**Comment by nmalacarne** [comment]
@eruanntion I set up a fresh project today using sass instead of stylus, and I am running into the same problems that you are. I am by no means a SASS user, but I will tinker some more with it this week and see if I can figure anything out.

**Comment by eruanntion** [comment]
@nmalacarne This is what I figured out so far. Mincer macros expressions will work, but only inside base scss files. But if use the same expressions inside partials which will be imported with @import keyword, they won't be compiled at all. Syntax you proposed won't work either way.
